name: islami
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  cupertino_icons: ^1.0.2
  animated_custom_dropdown: ^3.0.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/font/
    - assets/files/

  fonts:
    - family: "El Messiri"
      fonts:
        - asset: assets/font/ElMessiri-Bold.ttf
        - asset: assets/font/ElMessiri-Medium.ttf
        - asset: assets/font/ElMessiri-Regular.ttf
        - asset: assets/font/ElMessiri-SemiBold.ttf
